### ISSUE TITLE
Create the CloudWatch Event via CloudFormation

### ISSUE THREAD

**Issue by cristim** [bbc/chaos-lambda#3]
CloudFormation now supports setting up the event out of the box.

You can have a look at how I did it for one of my projects: https://github.com/cristim/autospotting/blob/master/cloudformation/stacks/AutoSpotting/template.json#L148

**Comment by pclifford** [comment]
Excellent, thank-you!  I've updated the CloudFormation stack to include the rule, and updated the documentation to match.
