### ISSUE TITLE
Provide clickable stack launch URLs on Github

### ISSUE THREAD

**Issue by cristim** [bbc/chaos-lambda#5]
The stack could be launched from the main Github page based on the README, using a template URL pointing to a bucket in S3, much like done here:
https://downloads.dcos.io/dcos/EarlyAccess/commit/14509fe1e7899f439527fb39867194c7a425c771/aws.html

Here's how I use the same approach [on one of my projects](https://github.com/cristim/autospotting#getting-started)

**Comment by stephegn** [comment]
We are closing old issues. Please let us know if this is still something that impacts you and we can re-open it.
