### ISSUE TITLE
Enable opt-in mode on a per-auto-scaling group mode

### ISSUE THREAD

**Issue by cristim** [bbc/chaos-lambda#6]
In my environment I would prefer(at least at first) to run this in a controlled manner, in order to detect configuration drift that would make new machines fail to set up and enter a spinning state.
- only run on a given day(or days) of the week, at a given time when I am likely available for fixing any issues it may find, for example at 10 AM on working days. This can be set up using a custom cron rule in the event generator.
- always terminate a single node from each of the AutoScaling groups where it is enabled in order to check if a new node would still be able to start and replace it.
- the enabled groups (or their instances, whichever is easier) should be selected using tags
- it should be an opt-in, so other groups would not be touched

**Comment by pclifford** [comment]
I've committed a change introducing a `DefaultMode` parameter, described in a bit more detail in #2, which you can set to `off` to get this opt-in behaviour.  Does that cover what you're looking for?
