### ISSUE TITLE
python3 upgrade 

### ISSUE THREAD

**Issue by yezen-alnafei** [bbc/chaos-lambda#9]
Hey, we’re currently upgrading our Lambda’s nodejs runtime versions. We noticed we have a Lambda that is based of the chaos-lambda-repo which uses the Python2.7 runtime. However, in June 2021 AWS will be dropping support for Python2. Are there plans to be upgrading the repo Python3?

**Comment by stephegn** [comment]
This was fixed in https://github.com/bbc/chaos-lambda/commit/96f1f2296aa0a4cacef4103557c8abcb82c884ed
